commerce_tax.commerce_tax_type.plugin.taxjar:
  type: commerce_tax_type_configuration
  mapping:
    api_key:
      type: string
      label: 'API Token'
    enable_calculation:
      type: boolean
      label: 'Enable sales tax calculation with TaxJar'
    enable_reporting:
      type: boolean
      label: 'Enable sales tax reporting with TaxJar'
    address_mode:
      type: string
      label: 'Ship from address mode'
